### ISSUE TITLE
requests version breaking mopidy-gmusic

### ISSUE THREAD

**Issue by lingnand** [mopidy/homebrew-mopidy#10]
After `brew install` mopidy I installed `mopidy-gmusic` according to the instructions on their [Github page](https://github.com/mopidy/mopidy-gmusic). Upon starting mopidy I'm greeted by these error messages:

```
Disabled extension gmusic: (requests 2.9.1 (/usr/local/lib/python2.7/site-packages), Requirement.parse('requests!=1.2.0,!=2.2.1,<2.8.0,>=1.1.0'), set(['gmusicapi']))
```

Right now I've worked around the problem by checking out the last version with requests 2.7.0 (1f40cedb815074f96efd891da1beb884dee7f89e) and reinstalling mopidy.

**Comment by jodal** [comment]
I think the issue should be opened with gmusicapi, which is the one saying that latest and greatest isn't good enough.

**Comment by JesseFarebro** [comment]
I don't even see the `mopidy-gmusic` plugin in the repository anymore?

**Comment by jodal** [comment]
@JesseFarebro mopidy-gmusic has never been in this repo. I think the problem was with the python-requests version installed by other Mopidy deps in this repo combined with mopidy-gmusic and gmusicapi installed with pip.

@lynnard Looks like the current gmusicapi version doesn't limit the upper version of requests, so closing this.
