### ISSUE TITLE
Cannot install via brew

### ISSUE THREAD

**Issue by n3rdly** [mopidy/homebrew-mopidy#27]
Mac OSX 10.13.4

➜ python3 --version
Python 3.6.5

➜ python2 --version
Python 2.7.15

`➜ brew install mopidy
==> Installing mopidy from mopidy/mopidy
==> Installing dependencies for mopidy/mopidy/mopidy: mopidy/mopidy/python-pykka, mopidy/mopidy/python-backports-abc, mopidy/mopidy/python-backports-ssl-match-hostname, mopidy/mopidy/python-certifi, mopidy/mopidy/python-six, mopidy/mopidy/python-singledispatch, mopidy/mopidy/python-tornado, mopidy/mopidy/python-requests
==> Installing mopidy/mopidy/mopidy dependency: mopidy/mopidy/python-pykka
==> Downloading https://files.pythonhosted.org/packages/source/P/Pykka/Pykka-1.2.1.tar.gz
==> Downloading from https://files.pythonhosted.org/packages/70/f7/bb8fc78fc52a50f66dda4260f8726c62267
######################################################################## 100.0%
Error: Empty installation`

**Comment by johnnynia** [comment]
Same here.

Mac OSX 10.13.4
Python 2.7.15

```sh
$ brew install mopidy/mopidy/python-pykka

==> Installing python-pykka from mopidy/mopidy
==> Downloading https://files.pythonhosted.org/packages/source/P/Pykka/Pykka-1.2.1.tar.gz
Already downloaded: /Users/jn/Library/Caches/Homebrew/python-pykka-1.2.1.tar.gz

Error: Empty installation
```

**Comment by n3rdly** [comment]
Steps tried; 
`$ rm -rf /Users/<myuseraccount>/Library/Caches/Homebrew/python-pykka-1.2.1.tar.gz`
` $ brew update; brew upgrade; brew prune; brew cleanup; brew doctor`
` $ brew uninstall --ignore-dependencies gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-python && brew install mopidy`

**Comment by jodal** [comment]
It was about time to brush up this Homebrew tap a bit...

### For Homebrew maintainers

According to https://docs.brew.sh/Python-for-Formula-Authors, Python applications should be installed in virtualenvs, and Python libraries (or more specifically, bindings, the only kind of Python libraries that Homebrew is interested in including) should preferably be installed in `libexec` with a `.pth` file adding the `libexec` dir to the `PYTHONPATH`. As Mopidy is an application with a extension architecture, it cannot easily be hidden away in a virtualenv, as it would then neither find Homebrew-installed bindings like `gi`, or Homebrew- or pip-installed Mopidy extensions, as they would all live outside Mopidy's virtualenv.

Thus, I've revamped all the formulas in this tap to install itself and all of its pure-Python dependencies into a `libexec` dir, and then add a `homebrew-$formula.pth` file to make it all globally importable without cluttering the global `site-packages` directory.

### Upgrade note for users

You can upgrade to the new and fixed Mopidy formulas by running:

```
brew upgrade
```

#### `_gi` import error

If you get an `ImportError: cannot import name _gi`, you need to reinstall `gobject3` with Python 2 support:

```
brew reinstall pygobject3 --with-python@2
```

Afterwards, `brew test pygobject3` should output:

```
Testing pygobject3
==> python3 test.py
==> python2.7 test.py
```

And `mopidy` should hopefully start without issues.

I believe this issue was caused by Homebrew's shuffling of python, python@2 and python@3 earlier this spring.

#### Old `*.pyc` files causing confusion

When running `mopidy` after the upgrade, you might see error messages about either:

- `RequestsDependencyWarning`
- `Setup of extension from entry point ... failed`

In these case you need to clear out `*.pyc` remnants of the old formula versions by running:

```
pyclean /usr/local/lib/python2.7/site-packages
```

If you want to clean up even a bit more, you can remove what should now, after the upgrade, be empty directory trees:

```
cd /usr/local/lib/python2.7/site-packages && rm -rf backports/ssl_match_hostname certifi cffi mopidy mopidy_dirble mopidy_notifier mopidy_soundcloud mopidy_spotify pycparser pylast pykka requests spotify tornado
```

This issue is caused by uninstalling Homebrew formulas that have their Python files symlinked to `/usr/local/lib/python2.7/site-packages`, and thus `*.pyc` files created there, outside the control of Homebrew. This should no longer be an issue, as all formulas in this tap now keep their files in the cellar, only adding a `homebrew-$formula.pth` file to `/usr/local/lib/python2.7/site-packages`. Thus, any `*.pyc` files are kept inside the cellar, and will be uninstalled together with the package.

**Comment by n3rdly** [comment]
Thank you for fixing this!!! ^_^

**Comment by ryanvirtue** [comment]
Thanks @jodal !!!!

**Comment by johnnynia** [comment]
Wow, thank you! 😃🎉

**Comment by jodal** [comment]
Thank you for the thanks! No better way to start the day than to wake up to this kind of feedback :-)

**Comment by seanorama** [comment]
This fixed my install too!:
`brew reinstall pygobject3 --with-python@2`

But took a while to find the solution. Could we get that in the docs?
https://docs.mopidy.com/en/latest/installation/osx/
